# Generated by Django 2.1.8 on 2019-04-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало работ')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание работ')),
                ('yes_processed_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Обработанные строки')),
                ('not_processed_rows', models.PositiveIntegerField(blank=True, null=True, verbose_name='Удаленные записи')),
                ('log_text', models.TextField(blank=True, null=True, verbose_name='Лог')),
                ('ready', models.BooleanField(blank=True, null=True, verbose_name='Работа завершена')),
            ],
            options={
                'verbose_name': 'работу',
                'verbose_name_plural': 'работа',
                'ordering': ['id'],
            },
        ),
    ]
