# Generated by Django 2.2 on 2019-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeworker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tworker',
            name='ready',
            field=models.BooleanField(blank=True, null=True, verbose_name='Работа завершена'),
        ),
        migrations.AlterField(
            model_name='tworker',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание работ'),
        ),
        migrations.AlterField(
            model_name='tworker',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работ'),
        ),
        migrations.AlterField(
            model_name='tworker',
            name='log_text',
            field=models.TextField(blank=True, null=True, verbose_name='Лог'),
        ),
        migrations.AlterField(
            model_name='tworker',
            name='not_processed_rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Удаленные записи'),
        ),
        migrations.AlterField(
            model_name='tworker',
            name='yes_processed_rows',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Обработанные строки'),
        ),
    ]
