# Generated by Django 2.2 on 2019-04-02 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeworker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tworker',
            options={'ordering': ['id'], 'verbose_name': 'работу', 'verbose_name_plural': 'работа'},
        ),
        migrations.AlterField(
            model_name='tworker',
            name='not_processed_rows',
            field=models.PositiveIntegerField(help_text='Не удачно обработанные строки', verbose_name='Не удачно обработанные строки'),
        ),
    ]
