# Generated by Django 2.2 on 2019-04-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='Название организации', max_length=50, null=True, unique=True, verbose_name='Название организации'),
        ),
    ]
