# Generated by Django 2.1.8 on 2019-04-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateField(help_text='Дата начала', verbose_name='Дата начала')),
                ('dateend', models.DateField(help_text='Дата окончания', verbose_name='Дата окончания')),
                ('order', models.ForeignKey(help_text='Заказ', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Период дат',
                'verbose_name_plural': 'Период дат',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numname', models.PositiveIntegerField(help_text='Номер цеха', unique=True, verbose_name='Номер цеха')),
                ('name', models.CharField(blank=True, help_text='Словесное обозначение цеха', max_length=100, null=True, verbose_name='Название')),
                ('fullname', models.CharField(blank=True, help_text='Полное словесное обозначение цеха', max_length=200, null=True, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Цех',
                'verbose_name_plural': 'Цех',
                'ordering': ['numname'],
            },
        ),
        migrations.AddField(
            model_name='daterange',
            name='workshop',
            field=models.ForeignKey(help_text='Цех', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='graph.Workshop', verbose_name='Цех'),
        ),
    ]
