# Generated by Django 2.2 on 2019-04-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandartDetailCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.PositiveIntegerField(blank=True, help_text='ID', null=True, verbose_name='ID')),
                ('shipment_from', models.DateField(blank=True, null=True, verbose_name='Отгрузка от')),
                ('shipment_to', models.DateField(blank=True, null=True, verbose_name='Отгрузка до')),
                ('product', models.CharField(max_length=100, verbose_name='продукция')),
                ('counterparty', models.CharField(blank=True, max_length=50, null=True, verbose_name='контрагент')),
                ('order_number', models.PositiveIntegerField(blank=True, help_text='№ Заказа', null=True, verbose_name='№ Заказа')),
                ('amount', models.PositiveIntegerField(blank=True, help_text='Кол-во', null=True, verbose_name='Кол-во')),
                ('sz', models.PositiveIntegerField(blank=True, help_text='СЗ', null=True, verbose_name='СЗ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказ',
                'ordering': ['fid'],
            },
        ),
    ]
