# Generated by Django 2.2 on 2019-04-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190402_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartdetailcreator',
            name='counterparty',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='контрагент'),
        ),
    ]
