# Generated by Django 2.1.8 on 2019-04-03 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officenotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentfrom', models.DateField(help_text='Дата служебной записки, указаннная в ней', verbose_name='Отгрузка "от"')),
                ('shipmentto', models.DateField(help_text='Дата служебной записки, указаннная в ней', verbose_name='Отгрузка "до"')),
                ('product', models.CharField(help_text='Название продукта', max_length=100, verbose_name='Продукция')),
                ('ordernum', models.PositiveIntegerField(blank=True, help_text='Оригинальный номер папки', null=True, verbose_name='№ Заказа')),
                ('quantity', models.FloatField(blank=True, help_text='Количество изделий', null=True, verbose_name='Кол-во')),
                ('pickingplan', models.DateField(blank=True, help_text='Комплектовочные План', null=True, verbose_name='Комплектовочные План')),
                ('pickingpercent', models.PositiveIntegerField(blank=True, help_text='Комплектовочные %', null=True, verbose_name='Комплектовочные %')),
                ('pickingfact', models.DateField(blank=True, help_text='Комплектовочные Факт', null=True, verbose_name='Комплектовочные Факт')),
                ('shippingplan', models.DateField(blank=True, help_text='Отгрузочные План', null=True, verbose_name='Отгрузочные План')),
                ('shippingpercent', models.PositiveIntegerField(blank=True, help_text='Отгрузочные %', null=True, verbose_name='Отгрузочные %')),
                ('shippingfact', models.DateField(blank=True, help_text='Отгрузочные Факт', null=True, verbose_name='Отгрузочные Факт')),
                ('engineeringplan', models.DateField(blank=True, help_text='Конструкторская План', null=True, verbose_name='Конструкторская План')),
                ('engineeringpercent', models.PositiveIntegerField(blank=True, help_text='Конструкторская %', null=True, verbose_name='Конструкторская %')),
                ('engineeringfact', models.DateField(blank=True, help_text='Конструкторская Факт', null=True, verbose_name='Конструкторская Факт')),
                ('drawingchangepercent', models.PositiveIntegerField(blank=True, help_text='Изменения чертежей %', null=True, verbose_name='Изменения чертежей %')),
                ('drawingchangefact', models.DateField(blank=True, help_text='Изменения чертежей Факт', null=True, verbose_name='Изменения чертежей Факт')),
                ('materialplan', models.DateField(blank=True, help_text='Материалы План', null=True, verbose_name='Материалы План')),
                ('materialfact', models.DateField(blank=True, help_text='Материалы Факт', null=True, verbose_name='Материалы Факт')),
                ('tableid', models.PositiveIntegerField(help_text='id в таблице', unique=True, verbose_name='id в таблице')),
                ('firstofficenote', models.ForeignKey(help_text='Служебная записка', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='officenotes.OfficeNote', verbose_name='Служебная записка')),
                ('otherofficenote', models.ManyToManyField(blank=True, related_name='officenotes', to='officenotes.OfficeNote', verbose_name='Дополнительные служебные записки')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['ordernum'],
            },
        ),
    ]
