# Generated by Django 2.1.8 on 2019-04-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['tableid'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
