# Generated by Django 2.2 on 2019-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190404_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready',
            field=models.BooleanField(default=1, verbose_name='Готов'),
            preserve_default=False,
        ),
    ]
