# Generated by Django 2.2 on 2019-04-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, help_text='Номер служебной записки', null=True, unique=True, verbose_name='Номер служебной записки')),
                ('date', models.DateField(blank=True, help_text='Дата служебной записки, указаннная в ней', null=True, verbose_name='Дата служебной записки')),
                ('datereceiving', models.DateField(blank=True, help_text='Дата получения служебной записки, указанная в почте', null=True, verbose_name='Дата получения служебной записки')),
                ('filepath', models.CharField(blank=True, help_text='Путь к файлу', max_length=100, null=True, verbose_name='Путь к файлу')),
                ('oncustomer', models.ForeignKey(blank=True, help_text='Заказчик', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'служебную записку',
                'verbose_name_plural': 'Служебные записки',
                'ordering': ['num'],
            },
        ),
    ]
