# Generated by Django 2.1.8 on 2019-04-04 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officenote',
            name='oncustomer',
            field=models.ForeignKey(blank=True, help_text='Заказчик', max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer', verbose_name='Заказчик'),
        ),
    ]
