# Generated by Django 2.2 on 2019-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officenote',
            name='datereceiving',
            field=models.DateField(blank=True, help_text='Дата получения служебной записки, указанная в почте', null=True, verbose_name='Дата получения служебной записки'),
        ),
    ]
