# Generated by Django 2.1.8 on 2019-04-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officenotes', '0002_auto_20190404_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='officenote',
            name='filepath',
            field=models.CharField(blank=True, help_text='Путь к файлу', max_length=100, null=True, verbose_name='Путь к файлу'),
        ),
    ]
