# Generated by Django 2.2 on 2019-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officenotes', '0002_auto_20190403_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officenote',
            name='date',
            field=models.DateField(blank=True, help_text='Дата служебной записки, указаннная в ней', null=True, verbose_name='Дата служебной записки'),
        ),
    ]
